######################################################################
#
# File name : AXIS_MULTIPLIER_TB_simulate.do
# Created on: Tue Jan 14 15:53:33 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L xbip_utils_v3_0_9 -L xbip_pipe_v3_0_5 -L xbip_bram18k_v3_0_5 -L mult_gen_v12_0_14 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.AXIS_MULTIPLIER_TB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {AXIS_MULTIPLIER_TB_wave.do}

view wave
view structure
view signals

do {AXIS_MULTIPLIER_TB.udo}

run 1000ns
