######################################################################
#
# File name : AXIS_MULTIPLIER_TB_wave.do
# Created on: Tue Jan 14 15:53:33 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
