######################################################################
#
# File name : AXIS_MULTIPLIER_TB_compile.do
# Created on: Tue Jan 14 15:53:30 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog -64 -incr -work xil_defaultlib  \
"../../../../../rtl/axis_control.v" \

vcom -64 -93 -work xil_defaultlib  \
"../../../../AXIS_MULTIPLIER.srcs/sources_1/bd/AXIS_MULTIPLIER/ip/AXIS_MULTIPLIER_mult_gen_0_0/sim/AXIS_MULTIPLIER_mult_gen_0_0.vhd" \

vlog -64 -incr -work xil_defaultlib  \
"../../../../AXIS_MULTIPLIER.srcs/sources_1/bd/AXIS_MULTIPLIER/ip/AXIS_MULTIPLIER_axis_control_0_0/sim/AXIS_MULTIPLIER_axis_control_0_0.v" \
"../../../../AXIS_MULTIPLIER.srcs/sources_1/bd/AXIS_MULTIPLIER/sim/AXIS_MULTIPLIER.v" \
"../../../../AXIS_MULTIPLIER.srcs/sources_1/bd/AXIS_MULTIPLIER/hdl/AXIS_MULTIPLIER_wrapper.v" \
"../../../../../sim/AXIS_MULTIPLIER_TB.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

