# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AXIS_MULTIPLIER/AXIS_MULTIPLIER.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXIS_MULTIPLIER || ORIG_REF_NAME==AXIS_MULTIPLIER} -quiet] -quiet

# IP: bd/AXIS_MULTIPLIER/ip/AXIS_MULTIPLIER_mult_gen_0_0/AXIS_MULTIPLIER_mult_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXIS_MULTIPLIER_mult_gen_0_0 || ORIG_REF_NAME==AXIS_MULTIPLIER_mult_gen_0_0} -quiet] -quiet

# IP: bd/AXIS_MULTIPLIER/ip/AXIS_MULTIPLIER_axis_control_0_0/AXIS_MULTIPLIER_axis_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AXIS_MULTIPLIER_axis_control_0_0 || ORIG_REF_NAME==AXIS_MULTIPLIER_axis_control_0_0} -quiet] -quiet

# XDC: bd/AXIS_MULTIPLIER/AXIS_MULTIPLIER_ooc.xdc
